apiVersion: v1
kind: Service
metadata:
  name: {{ include "plausible.fullname" . }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plausible.service.type }}
  ports:
    - port: {{ .Values.plausible.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plausible.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plausible.fullname" . }}-db
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plausible.service.type }}
  ports:
    - port: 5432
      targetPort: db
      protocol: TCP
      name: db
  selector:
    {{- include "plausible.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plausible.fullname" . }}-eventdb
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plausible.service.type }}
  ports:
    - port: 8123
      targetPort: eventdb
      protocol: TCP
      name: eventdb
  selector:
    {{- include "plausible.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: eventdb
...
