{{- if .Values.plausible.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plausible.serviceAccountName" . }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
  {{- with .Values.plausible.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
...
